/**
 * Action Types Enum
 * Centralizes all action type strings to prevent typos.
 * @readonly
 * @enum {string}
 */
export const ActionTypes = {
  CHANGE_SCENE: 'CHANGE_SCENE',
  UPDATE_PLAYER: 'UPDATE_PLAYER',
  UPDATE_BAND: 'UPDATE_BAND',
  UPDATE_SOCIAL: 'UPDATE_SOCIAL',
  UPDATE_SETTINGS: 'UPDATE_SETTINGS',
  SET_MAP: 'SET_MAP',
  SET_GIG: 'SET_GIG',
  START_GIG: 'START_GIG',
  SET_SETLIST: 'SET_SETLIST',
  SET_LAST_GIG_STATS: 'SET_LAST_GIG_STATS',
  SET_ACTIVE_EVENT: 'SET_ACTIVE_EVENT',
  ADD_TOAST: 'ADD_TOAST',
  REMOVE_TOAST: 'REMOVE_TOAST',
  SET_GIG_MODIFIERS: 'SET_GIG_MODIFIERS',
  LOAD_GAME: 'LOAD_GAME',
  RESET_STATE: 'RESET_STATE',
  APPLY_EVENT_DELTA: 'APPLY_EVENT_DELTA',
  POP_PENDING_EVENT: 'POP_PENDING_EVENT',
  CONSUME_ITEM: 'CONSUME_ITEM',
  ADVANCE_DAY: 'ADVANCE_DAY',
  ADD_COOLDOWN: 'ADD_COOLDOWN',
  START_TRAVEL_MINIGAME: 'START_TRAVEL_MINIGAME',
  COMPLETE_TRAVEL_MINIGAME: 'COMPLETE_TRAVEL_MINIGAME',
  START_ROADIE_MINIGAME: 'START_ROADIE_MINIGAME',
  COMPLETE_ROADIE_MINIGAME: 'COMPLETE_ROADIE_MINIGAME',
  UNLOCK_TRAIT: 'UNLOCK_TRAIT',

  ADD_VENUE_BLACKLIST: 'ADD_VENUE_BLACKLIST',
  ADD_QUEST: 'ADD_QUEST',
  ADVANCE_QUEST: 'ADVANCE_QUEST',
  COMPLETE_QUEST: 'COMPLETE_QUEST',
  FAIL_QUESTS: 'FAIL_QUESTS'
}
